
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 29 12:52:05 CDT 2014
//----------------------------------------------------

package mx.ipn.hock5.utils;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int LT = 8;
  public static final int NE = 11;
  public static final int PUNTOYCOMA = 14;
  public static final int ELSE = 5;
  public static final int PLUS = 15;
  public static final int RPAREN = 20;
  public static final int WHILE = 3;
  public static final int POW = 21;
  public static final int RKEY = 12;
  public static final int IF = 4;
  public static final int LPAREN = 19;
  public static final int GT = 6;
  public static final int LKEY = 13;
  public static final int LE = 9;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int GE = 7;
  public static final int MINUS = 16;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int EQ = 10;
  public static final int SALTOLINEA = 26;
  public static final int VAR = 22;
  public static final int UNARYMINUS = 24;
}

