
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 21 05:53:19 CDT 2014
//----------------------------------------------------

package mx.ipn.hock5.utils;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int NUMBER = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
}

