
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 01 18:19:48 CDT 2014
//----------------------------------------------------

package mx.ipn.proyectoFinal.utils;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int TABLE = 2;
  public static final int EOF = 0;
}

