
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 02 01:27:11 CDT 2014
//----------------------------------------------------

package mx.ipn.proyectoFinal.utils;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int NE = 18;
  public static final int LT = 14;
  public static final int PUNTO = 7;
  public static final int OR = 19;
  public static final int CAMPO = 10;
  public static final int PAR_I = 8;
  public static final int SELECCION = 4;
  public static final int NOT = 21;
  public static final int PAR_D = 9;
  public static final int GT = 12;
  public static final int LE = 15;
  public static final int TABLE = 2;
  public static final int COMA = 6;
  public static final int EOF = 0;
  public static final int NUMBER = 11;
  public static final int PROYECCION = 3;
  public static final int GE = 13;
  public static final int error = 1;
  public static final int LIKE = 17;
  public static final int EQ = 16;
  public static final int JOIN = 5;
}

